services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: toto
      POSTGRES_USER: frozar
      POSTGRES_DB: diesel-demo

  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - "5050:80"
    depends_on:
      - "db"
    environment:
      PGADMIN_DEFAULT_EMAIL: fabien@flaxib.re
      PGADMIN_DEFAULT_PASSWORD: toto



